labels:
  - auto_merge

# マージするPRにつけるラベルの条件
# 上記の例では、 auto_merge_force OR ( auto_merge AND minor ) の条件に一致したらマージを行います。

merge_type: squash # マージモード (optional): merge, squash, rebase デフォルト: merge
delete_branch: delete # マージ後にブランチを削除するかどうか (optional): delete または 空欄
