name: Preview Deploy (only development)

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - development

jobs:
  preview-deploy:
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.labels.*.name, 'preview-deploy')
    steps:
      - uses: actions/checkout@v3
        with:
          repository: '${{ github.event.pull_request.head.repo.full_name }}'
          ref: '${{ github.event.pull_request.head.sha }}'
          lfs: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run generate:dev
      - run: "echo \"User-agent: *\nDisallow: /\" > ./dist/robots.txt"

      - name: Preview Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STOPCOVID19_TOKYO }}'
          projectId: stopcovid19-tokyo
          target: development
