name: Auto-i18n Generator

on:
  push:
    branches:
      - development

jobs:
  i18n-builder:
    if: false == contains(github.event.commits[0].message, 'Update assets/locales/ja.json')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v2
        with:
          ref: development
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install BeautifulSoup4
      - name: Run script
        run: |
          cd auto-i18n
          python i18n_generator.py
          cd ..
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update assets/locales/ja.json
          title: Update transration files
          labels: auto_merge
          branch-suffix: 'short-commit-hash'